#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          rappmanager
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Flower Platform app manager
# Description:       Flower Platform app manager
### END INIT INFO

NAME=rappmanager
DESC="Flower Platform app manager"
JAR_FILE=/opt/flower-platform/bin/rapp-manager.jar
DAEMON=/usr/bin/java
DAEMON_ARGS="-jar $JAR_FILE >> ~/log/$NAME.log 2>&1"
DAEMON_USER="flowerplatform"
PIDFILE=/var/run/$NAME.pid


do_start_cmd() {
    start-stop-daemon --start --chuid $DAEMON_USER --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS"
}

do_stop_cmd() {
    start-stop-daemon --stop --user $DAEMON_USER --pidfile $PIDFILE 
}
